### ISSUE TITLE
Execution Fails with Error

### ISSUE THREAD

**Issue by acornett21** [dci-labs/certification-lab-config#9]
After many times of creating and tearing down the VM, the same error still persists. 

```
+ exec dci-pipeline 'ocp-workload:ansible_inventory=~/certification-lab-config/inventories/pool/cluster1-workload.yml' 'ocp-workload:ansible_extravars=kubeconfig_path:~/cluster1/auth/kubeconfig' /home/vagrant/certification-lab-config/pipelines/workload-pipeline.yml
Traceback (most recent call last):
  File "/usr/bin/dci-pipeline", line 11, in <module>
    load_entry_point('dci-pipeline==0.9.0', 'console_scripts', 'dci-pipeline')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/dcipipeline/main.py", line 29, in <module>
    from ansible.cli import CLI
ModuleNotFoundError: No module named 'ansible'
```

Not sure what piece of the instructions or of the OS are missing.

**Comment by ramperher** [comment]
CC @tkrishtop @pierreblanc , in case you didn't see this.
